name: test slp_png

on:
  push:
    branches: [ "main" ]
    paths-ignore: ['README.md', '.gitignore', 'LICENSE']
  pull_request:
    branches: [ "main" ]
    paths-ignore: ['README.md', '.gitignore', 'LICENSE']

jobs:
  test_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: run docker to run test on archlinux
        run: |
          docker build --no-cache -t slp_png-linux _scripts/archlinux

  test_macOS:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        shell: bash
        run: |
          brew install zlib-ng libspng llvm
          cmake -B build -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S .
          cmake --build build --config Release
          build/test
          bash -c "shopt -s nullglob; for file in CI_TEST-*.png; do cmp $file CI_TEST.png; if [ \$? -ne 0 ]; then echo 'fail at: cmp $file CI_TEST.png'; exit 1; fi; done; shopt -u nullglob;"

