name: test slp_png

on:
  push:
    branches: [ "main" ]
    paths-ignore: ['README.md', '.gitignore', 'LICENSE']
  pull_request:
    branches: [ "main" ]
    paths-ignore: ['README.md', '.gitignore', 'LICENSE']

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: run docker
        run: |
          docker build --no-cache -t slp_png-linux _scripts/archlinux
          docker build --no-cache -t slp_png-macOS _scripts/macOS


